apiVersion: v1
kind: Pod
metadata:
  name: counter
spec:
  containers:
  - name: count
    image: busybox
    args:
    - /bin/sh
    - -c
    - >
      while sleep 60;
      do
        echo "$(date)" >> /output/date.log
      done      
    volumeMounts:
    - name: varlog
      mountPath: /output
  - name: count-log-1
    image: nginx
    volumeMounts:
    - name: varlog
      mountPath: /usr/share/nginx/html
  volumes:
  - name: varlog
    emptyDir: {}
